### ISSUE TITLE
Data Filter Feature Request

### ISSUE THREAD

**Issue by sresam89** [normaldotcom/cangaroo#7]
Could we add data filtering based on Frame IDs or the Raw byte, data-in-position?

I am open to collaborate on the work

**Comment by normaldotcom** [comment]
Hey! I just committed support for basic filtering -- based off of message ID, sender name. etc. I'm definitely open to merging in support for more sophisticated filtering however.

**Comment by normaldotcom** [comment]
Closed due to inactivity

**Comment by sresam89** [comment]
Thanks I will check and reply. thanks for the merge
